name: flutter_pubnub_chat
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0    
  intl: ^0.17.0  
  pubnub: ^3.1.0
  emoji_picker: ^0.1.0
  flutter_dotenv: ^3.1.0
  url_launcher: ^6.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/setup/
    - .env
